# OPTIONS

# Window Settings
[window]  			
width = 1920
height = 1080
fullscreen = 1

[graphics]
res_x = 1920
res_y = 1080
camera_tilt = 1	
vsync = 1	
show_fps = 1

# Input Settings
[input]
ms = 3500	# mouse sensitivity

