qbsp="./ericw-tools/qbsp"
vis="./ericw-tools/vis"
light="./ericw-tools/light"

qbsp_args = "-bspx -forcegoodtree"
vis_args=""
light_args="-bspx -lit -surflight_radiosity 1 -world_units_per_luxel 16 -extra4 -soft 5 -lightgrid -lightgrid_format octree"
